// components/widgets/MeetilySummary/MeetilySummaryWidget.tsx
"use client";

import React, { useState, useEffect, useRef, useLayoutEffect } from "react";
import { FileText, Loader2, Bot, RefreshCw, Download, Send, CheckCircle2, AlertCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import jsPDF from "jspdf";

interface Props {
  config: {
    widgetTitle: string;
    sendWhatsapp?: boolean;
    sendEmail?: boolean;
    sendTelegram?: boolean;
  };
}

interface SummaryEntry {
  meetingId: string;
  summary: string; // bisa plain text atau JSON string (Meetily format)
  timestamp: string;
}

// Tipe data Meetily structured summary
interface MeetilyBlock {
  id: string;
  type: "text" | "bullet";
  content: string;
  color?: string;
}

interface MeetilySection {
  title: string;
  blocks: MeetilyBlock[];
}

interface MeetilyStructured {
  MeetingName?: string;
  _section_order?: string[];
  [key: string]: MeetilySection | string | string[] | undefined;
}

type WidgetState = "idle" | "generating" | "ready";

// ── PDF Export ──────────────────────────────────────────────────────────────
function exportToPdf(entry: SummaryEntry) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── Header bar ──
  doc.setFillColor(109, 40, 217); // violet-700
  doc.rect(0, 0, pageW, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("NexaBrick IoT Platform", margin, 10);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Meeting Summary", margin, 17);
  y = 30;

  // ── Meta info ──
  doc.setTextColor(71, 85, 105); // slate-600
  doc.setFontSize(9);
  const formatted = (() => {
    try {
      return new Date(entry.timestamp).toLocaleString("id-ID", {
        day: "2-digit", month: "long", year: "numeric",
        hour: "2-digit", minute: "2-digit",
      });
    } catch { return entry.timestamp; }
  })();
  doc.text(`Meeting ID : ${entry.meetingId}`, margin, y);
  y += 5;
  doc.text(`Tanggal    : ${formatted}`, margin, y);
  y += 3;

  // ── Divider ──
  doc.setDrawColor(203, 213, 225); // slate-300
  doc.setLineWidth(0.3);
  doc.line(margin, y + 2, pageW - margin, y + 2);
  y += 8;

  // ── Content ──
  const structured = parseMeetilyFormat(entry.summary);

  const addText = (text: string, bold = false, indent = 0) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 10 : 9);
    doc.setTextColor(bold ? 30 : 51, bold ? 41 : 65, bold ? 59 : 85);
    const lines = doc.splitTextToSize(text, contentW - indent);
    lines.forEach((line: string) => {
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(line, margin + indent, y);
      y += bold ? 5.5 : 4.5;
    });
  };

  if (structured) {
    if (structured.MeetingName) {
      addText(structured.MeetingName as string, true);
      y += 2;
    }
    const order =
      structured._section_order ??
      Object.keys(structured).filter((k) => k !== "_section_order" && k !== "MeetingName");

    order.forEach((key) => {
      const section = structured[key] as MeetilySection | undefined;
      if (!section || typeof section !== "object") return;
      const visible = section.blocks?.filter((b) => b.content?.trim());
      if (!visible?.length) return;

      // Section title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(124, 58, 237); // violet-600
      if (y > 270) { doc.addPage(); y = margin; }
      doc.text(section.title.toUpperCase(), margin, y);
      y += 5;

      visible.forEach((block) => {
        const prefix = block.type === "bullet" ? "• " : "";
        addText(prefix + block.content, false, block.type === "bullet" ? 3 : 0);
      });
      y += 3;
    });
  } else {
    // Plain text fallback
    const lines = entry.summary.split("\n").filter((l) => l.trim());
    lines.forEach((line) => {
      const t = line.replace(/\*\*/g, "").replace(/\*/g, "").trim();
      const isHeader = !t.startsWith("-") && !t.startsWith("•") && !/^\d+\./.test(t);
      addText(isHeader ? t : "• " + t.replace(/^[-•]\s*|\d+\.\s*/, ""), isHeader);
    });
  }

  // ── Footer ──
  const totalPages = (doc.internal as { getNumberOfPages?: () => number }).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by NexaBrick AI  ·  ${formatted}  ·  Page ${i} of ${totalPages}`,
      margin,
      doc.internal.pageSize.getHeight() - 8
    );
  }

  const safeName = `meeting-summary-${entry.meetingId}-${Date.now()}.pdf`;
  doc.save(safeName);
}

// Parse summary — return Meetily structured object atau null kalau plain text
function parseMeetilyFormat(raw: string): MeetilyStructured | null {
  try {
    const obj = JSON.parse(raw);
    if (obj && typeof obj === "object" && "_section_order" in obj) return obj;
  } catch { /* bukan JSON */ }
  return null;
}

export const MeetilySummaryWidget = ({ config }: Props) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [state, setState] = useState<WidgetState>("idle");
  const [summary, setSummary] = useState<SummaryEntry | null>(null);
  const [generatingId, setGeneratingId] = useState<string | null>(null);
  const [notifStatus, setNotifStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");

  const [sz, setSz] = useState({ title: 13, header: 42, body: 12, sub: 10 });

  useLayoutEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const update = () => {
      const { width, height } = el.getBoundingClientRect();
      setSz({
        title: Math.max(11, Math.min(width * 0.04, 15)),
        header: Math.max(36, Math.min(height * 0.15, 52)),
        body: Math.max(10, Math.min(width * 0.033, 13)),
        sub: Math.max(9, Math.min(width * 0.028, 11)),
      });
    };
    const ro = new ResizeObserver(update);
    ro.observe(el);
    update();
    return () => ro.disconnect();
  }, []);

  // Fetch latest summary on mount
  useEffect(() => {
    const fetchLatest = async () => {
      try {
        const res = await fetch("/api/meetily/summary");
        if (!res.ok) return;
        const json = await res.json();
        if (json.data) { setSummary(json.data); setState("ready"); }
      } catch { /* silent */ }
    };
    fetchLatest();
  }, []);

  // Send notification to participants after summary is ready
  const sendNotification = async (entry: SummaryEntry) => {
    const { sendWhatsapp, sendEmail, sendTelegram } = config;
    if (!sendWhatsapp && !sendEmail && !sendTelegram) return;

    setNotifStatus("sending");
    try {
      const res = await fetch("/api/meetily/summary/notify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          meetingId: entry.meetingId,
          summary: entry.summary,
          sendWhatsapp: sendWhatsapp ?? false,
          sendEmail: sendEmail ?? false,
          sendTelegram: sendTelegram ?? false,
        }),
      });
      setNotifStatus(res.ok ? "sent" : "error");
    } catch {
      setNotifStatus("error");
    }
  };

  // SSE: terima generating + summary events
  useEffect(() => {
    const es = new EventSource("/api/meetily/summary/stream");
    es.onmessage = (e) => {
      try {
        const data = JSON.parse(e.data);
        if (data.type === "generating") {
          setState("generating");
          setNotifStatus("idle");
          setGeneratingId(data.meetingId ?? null);
        } else if (data.type === "summary") {
          const entry: SummaryEntry = {
            meetingId: data.meetingId,
            summary: data.summary,
            timestamp: data.timestamp,
          };
          setSummary(entry);
          setState("ready");
          setGeneratingId(null);
          sendNotification(entry);
        }
      } catch { /* ignore */ }
    };
    es.onerror = () => es.close();
    return () => es.close();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config.sendWhatsapp, config.sendEmail, config.sendTelegram]);

  const formatTime = (ts: string) => {
    try {
      return new Date(ts).toLocaleString("id-ID", {
        day: "2-digit", month: "short", year: "numeric",
        hour: "2-digit", minute: "2-digit",
      });
    } catch { return ""; }
  };

  // Render Meetily structured format
  const renderStructured = (obj: MeetilyStructured) => {
    const order = obj._section_order ?? Object.keys(obj).filter((k) => k !== "_section_order" && k !== "MeetingName");

    return (
      <div className="space-y-3">
        {obj.MeetingName && (
          <p
            className="font-semibold text-slate-800 dark:text-slate-200 border-b border-slate-200 dark:border-slate-700 pb-1"
            style={{ fontSize: sz.body + 1 }}
          >
            {obj.MeetingName as string}
          </p>
        )}
        {order.map((key) => {
          const section = obj[key] as MeetilySection | undefined;
          if (!section || typeof section !== "object") return null;
          const visibleBlocks = section.blocks?.filter((b) => b.content?.trim());
          if (!visibleBlocks || visibleBlocks.length === 0) return null;

          return (
            <div key={key}>
              <p
                className="font-semibold text-slate-600 dark:text-slate-400 mb-1 uppercase tracking-wide"
                style={{ fontSize: sz.sub }}
              >
                {section.title}
              </p>
              <div className="space-y-0.5">
                {visibleBlocks.map((block, i) =>
                  block.type === "bullet" ? (
                    <p
                      key={i}
                      className="flex gap-1.5 text-slate-700 dark:text-slate-300 leading-snug"
                      style={{ fontSize: sz.body }}
                    >
                      <span className="text-slate-400 flex-shrink-0">•</span>
                      <span>{block.content}</span>
                    </p>
                  ) : (
                    <p
                      key={i}
                      className="text-slate-700 dark:text-slate-300 leading-snug"
                      style={{ fontSize: sz.body }}
                    >
                      {block.content}
                    </p>
                  )
                )}
              </div>
            </div>
          );
        })}
      </div>
    );
  };

  // Render plain text (fallback)
  const renderPlainText = (text: string) => {
    // Strip markdown bold/italic markers yang mungkin datang dari Groq
    const clean = (s: string) => s.replace(/\*\*/g, "").replace(/\*/g, "").trim();
    const lines = text.split("\n").filter((l) => l.trim());
    return (
      <div className="space-y-1">
        {lines.map((line, i) => {
          const t = clean(line);
          const isBullet = t.startsWith("-") || t.startsWith("•") || /^\d+\./.test(t);
          return (
            <p
              key={i}
              className={
                isBullet
                  ? "flex gap-1.5 text-slate-700 dark:text-slate-300 leading-snug"
                  : "font-medium text-slate-800 dark:text-slate-200 mt-1 leading-snug"
              }
              style={{ fontSize: sz.body }}
            >
              {isBullet ? (
                <>
                  <span className="text-slate-400 flex-shrink-0">•</span>
                  <span>{t.replace(/^[-•]\s*|\d+\.\s*/, "")}</span>
                </>
              ) : t}
            </p>
          );
        })}
      </div>
    );
  };

  const renderSummary = (s: SummaryEntry) => {
    const structured = parseMeetilyFormat(s.summary);
    return structured ? renderStructured(structured) : renderPlainText(s.summary);
  };

  return (
    <div
      ref={containerRef}
      className="relative w-full h-full bg-card border border-border/60 rounded-xl shadow-sm overflow-hidden"
    >
      {/* Header */}
      <div
        className="absolute top-0 left-0 right-0 px-3 flex items-center justify-between
                   bg-slate-50/50 dark:bg-slate-900/30 border-b border-slate-200/40 dark:border-slate-700/40"
        style={{ height: sz.header }}
      >
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <Bot className="text-violet-500 flex-shrink-0" style={{ width: 15, height: 15 }} />
          <h3
            className="font-medium truncate text-slate-700 dark:text-slate-300"
            style={{ fontSize: sz.title }}
          >
            {config.widgetTitle}
          </h3>
        </div>

        <div className="flex items-center gap-2 flex-shrink-0">
          {state === "generating" && (
            <Badge variant="secondary" className="text-xs px-2 py-0 h-5 gap-1">
              <Loader2 className="h-2.5 w-2.5 animate-spin" />
              Generating...
            </Badge>
          )}
          {notifStatus === "sending" && (
            <Badge variant="secondary" className="text-xs px-2 py-0 h-5 gap-1">
              <Send className="h-2.5 w-2.5 animate-pulse" />
              Sending...
            </Badge>
          )}
          {notifStatus === "sent" && (
            <Badge className="bg-emerald-600 hover:bg-emerald-600 text-white text-xs px-2 py-0 h-5 gap-1">
              <CheckCircle2 className="h-2.5 w-2.5" />
              Sent
            </Badge>
          )}
          {notifStatus === "error" && (
            <Badge variant="destructive" className="text-xs px-2 py-0 h-5 gap-1">
              <AlertCircle className="h-2.5 w-2.5" />
              Notif Failed
            </Badge>
          )}
          {state === "ready" && summary && (
            <>
              {notifStatus === "idle" && (
                <Badge className="bg-emerald-600 hover:bg-emerald-600 text-white text-xs px-2 py-0 h-5">
                  Ready
                </Badge>
              )}
              <button
                onClick={() => exportToPdf(summary)}
                title="Download PDF"
                className="flex items-center gap-1 px-2 py-0.5 rounded text-xs
                           bg-violet-600 hover:bg-violet-700 active:scale-95
                           text-white transition-all duration-150 flex-shrink-0"
                style={{ fontSize: sz.sub }}
              >
                <Download style={{ width: 11, height: 11 }} />
                PDF
              </button>
            </>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="absolute inset-x-0 bottom-0 overflow-y-auto" style={{ top: sz.header }}>
        {state === "generating" ? (
          <div className="w-full h-full flex flex-col items-center justify-center gap-3 px-4">
            <div className="flex items-center gap-2 text-violet-500">
              <RefreshCw className="h-5 w-5 animate-spin" />
              <span className="text-slate-600 dark:text-slate-400" style={{ fontSize: sz.body }}>
                AI sedang membuat ringkasan rapat...
              </span>
            </div>
            {generatingId && (
              <span className="text-slate-400 dark:text-slate-600" style={{ fontSize: sz.sub }}>
                Meeting ID: {generatingId}
              </span>
            )}
          </div>
        ) : state === "ready" && summary ? (
          <div className="px-3 py-2">
            {/* Meta */}
            <div className="flex items-center justify-between mb-2">
              <span className="text-slate-400 dark:text-slate-600" style={{ fontSize: sz.sub }}>
                {formatTime(summary.timestamp)}
              </span>
              <span className="text-slate-400 dark:text-slate-600 truncate ml-2" style={{ fontSize: sz.sub }}>
                ID: {summary.meetingId}
              </span>
            </div>
            {renderSummary(summary)}
          </div>
        ) : (
          <div className="w-full h-full flex flex-col items-center justify-center gap-2">
            <FileText className="text-slate-300 dark:text-slate-600" style={{ width: 28, height: 28 }} />
            <p className="text-slate-400 text-center px-4" style={{ fontSize: sz.body }}>
              Ringkasan akan muncul setelah rapat selesai
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
